# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"\x17\n\x04\x46ile\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x1e\n\x07Request\x12\x13\n\x0brequestFile\x18\x02 \x01(\t22\n\x11\x43lientCallService\x12\x1d\n\x08sendFile\x12\x05.File\x1a\x08.Request\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILE']._serialized_start=17
  _globals['_FILE']._serialized_end=40
  _globals['_REQUEST']._serialized_start=42
  _globals['_REQUEST']._serialized_end=72
  _globals['_CLIENTCALLSERVICE']._serialized_start=74
  _globals['_CLIENTCALLSERVICE']._serialized_end=124
# @@protoc_insertion_point(module_scope)
